# Generated by Django 5.0.7 on 2024-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tipo_reporte', models.CharField(choices=[('mora_30', 'MORA 30'), ('especiales', 'ESPECIALES'), ('castigo', 'CASTIGO')], max_length=30)),
                ('chats', models.FileField(upload_to='', verbose_name='chats')),
                ('basedata', models.FileField(upload_to='', verbose_name='basedata')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
