# Generated by Django 5.1.1 on 2024-10-04 13:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import reportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('campaign', models.CharField(default='Sin Asignar', max_length=30, null=True)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.CharField(choices=[('trainee', 'TRAINEE'), ('junior', 'JUNIOR'), ('semisenior', 'SEMI SENIOR'), ('senior', 'SENIOR')], default='Sin Asignar', max_length=30, null=True)),
                ('last_rank', models.CharField(choices=[('trainee', 'TRAINEE'), ('junior', 'JUNIOR'), ('semisenior', 'SEMI SENIOR'), ('senior', 'SENIOR')], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to', related_name='usuario_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user', related_name='usuario_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SMSBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mora_30', 'MORA 30'), ('especiales', 'ESPECIALES'), ('castigo', 'CASTIGO'), ('multimarca', 'MULTIMARCA')], max_length=50)),
                ('sms_base', models.FileField(upload_to=reportes.models.ruta_dinamica)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(choices=[('mora_30', 'MORA 30'), ('especiales', 'ESPECIALES'), ('castigo', 'CASTIGO'), ('multimarca', 'MULTIMARCA')], max_length=15)),
                ('chats_file', models.FileField(upload_to='files/upload/chats/')),
                ('numero_inicio', models.CharField(blank=True, max_length=11)),
                ('numero_final', models.CharField(max_length=11)),
                ('hora', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte', to_field='name')),
            ],
        ),
    ]
