# Generated by Django 5.0.7 on 2024-07-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campaign', models.CharField(choices=[('mora_30', 'MORA 30'), ('especiales', 'ESPECIALES'), ('castigo', 'CASTIGO')], max_length=15)),
                ('chats_file', models.FileField(upload_to='files/chats')),
                ('envio_sms_file', models.FileField(upload_to='files/envio_sms')),
                ('hora', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte', to_field='name')),
            ],
        ),
    ]
