# Generated by Django 5.0.7 on 2024-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='chats_file',
            field=models.FileField(upload_to='files/chats/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='envio_sms_file',
            field=models.FileField(upload_to='files/envio_sms/'),
        ),
    ]
