# Generated by Django 5.0.7 on 2024-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportewhatsapp',
            name='basedata',
            field=models.FileField(upload_to='files/bases/'),
        ),
        migrations.AlterField(
            model_name='reportewhatsapp',
            name='chats',
            field=models.FileField(upload_to='files/chats'),
        ),
        migrations.AlterField(
            model_name='reportewhatsapp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
