# Generated by Django 5.1.1 on 2024-10-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('complete_access_to_reportes_app', 'Complete access to reportes app'), ('acces_to_customer_management', 'Access to customer management')]},
        ),
    ]
