# Generated by Django 5.1.2 on 2024-10-23 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.CharField(choices=[('trainee', 'TRAINEE'), ('junior', 'JUNIOR'), ('semisenior', 'SEMI SENIOR'), ('senior', 'SENIOR')], default='Sin Asignar', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('compliance', models.FloatField(default=0)),
                ('value_per_point', models.FloatField(default=0)),
                ('benefit', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_rank',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='points',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rank',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='chats_file',
            field=models.FileField(upload_to='upload/chats/'),
        ),
    ]
