# Generated by Django 5.0.7 on 2024-08-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporte_chats_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='chats_file',
            field=models.FileField(upload_to='files/upload/chats/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='envio_sms_file',
            field=models.FileField(upload_to='files/upload/envio_sms/'),
        ),
    ]
