# Generated by Django 5.0.7 on 2024-08-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_chats_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mora_30', 'MORA 30'), ('especiales', 'ESPECIALES'), ('castigo', 'CASTIGO'), ('base_general', 'BASE GENERAL')], max_length=50)),
                ('sms_base', models.FileField(upload_to='files/sms_databases')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte', to_field='name')),
            ],
        ),
    ]
