# Generated by Django 5.0.7 on 2024-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_smsbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='envio_sms_file',
        ),
        migrations.AlterField(
            model_name='smsbase',
            name='name',
            field=models.CharField(choices=[('mora_30', 'MORA 30'), ('especiales', 'ESPECIALES'), ('castigo', 'CASTIGO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smsbase',
            name='sms_base',
            field=models.FileField(upload_to='files/sms_databases/'),
        ),
    ]
