# Generated by Django 5.0.7 on 2024-08-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_remove_reporte_envio_sms_file_alter_smsbase_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='numero_final',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='numero_inicio',
            field=models.CharField(default='n/a', max_length=10),
            preserve_default=False,
        ),
    ]
