# Generated by Django 5.0.7 on 2024-08-05 20:47

import reportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_reporte_numero_final_reporte_numero_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='numero_final',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='numero_inicio',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='smsbase',
            name='sms_base',
            field=models.FileField(upload_to=reportes.models.ruta_dinamica),
        ),
    ]
