# Generated by Django 5.0.7 on 2024-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_reporte_numero_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='numero_inicio',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
