# Generated by Django 5.1 on 2024-08-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_scraper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scraper',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='name',
        ),
    ]
