# Generated by Django 5.1 on 2024-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_delete_scraper_remove_reporte_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
