# Generated by Django 5.1.1 on 2024-09-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0014_recursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recursos',
            new_name='Recurso',
        ),
    ]
