# Generated by Django 5.1.1 on 2024-09-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0015_rename_recursos_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='rresource_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
