# Generated by Django 5.1.1 on 2024-09-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0016_recurso_rresource_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='rresource_name',
            new_name='resource_name',
        ),
    ]
