# Generated by Django 5.1.1 on 2024-09-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0017_rename_rresource_name_recurso_resource_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
